services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=ace_root
      - MYSQL_DATABASE=ace_sem
      - MYSQL_USER=ace
      - MYSQL_PASSWORD=ace_pw
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
volumes:
  db_data:



