services:
  mysql:
    image: mysql:8.0
    container_name: sem_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ace_sem
      MYSQL_USER: ace
      MYSQL_PASSWORD: ace_pw
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sem_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data: